#!/bin/bash

[ -z `find /etc/crontab -mtime 0 ` ]   <<<< use md5sums

if [ $? -eq 0 ]
then
    echo "nothing has changed"
else
   echo "Mail envoyé le $(date)" | mail -s "/etc/crontab has changed" root
fi
# * 0 * * * /bin/sh /home/tnoah/04.sh > /dev/null 2>&1
